/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snap.care;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        table_update();
        table_update1();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Adminpage1 = new javax.swing.JLabel();
        lbl_doctors = new javax.swing.JLabel();
        lbl_users = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        pnlBody = new javax.swing.JPanel();
        jPanel_doctors = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctors_table = new javax.swing.JTable();
        jPanel_userqueries = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_queries = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        Adminpage1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        Adminpage1.setForeground(new java.awt.Color(255, 255, 255));
        Adminpage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Adminpage1.setText("<html>Admin<br>Page</html>");

        lbl_doctors.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lbl_doctors.setForeground(new java.awt.Color(255, 255, 255));
        lbl_doctors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_doctors.setText("Doctors's");
        lbl_doctors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_doctors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_doctorsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_doctorsMouseEntered(evt);
            }
        });

        lbl_users.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lbl_users.setForeground(new java.awt.Color(255, 255, 255));
        lbl_users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_users.setText("<html>User's<br>Queries</html>");
        lbl_users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_usersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_usersMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_doctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_users)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Adminpage1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Adminpage1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(lbl_doctors, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(lbl_users, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        pnlBody.setLayout(new java.awt.CardLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel4.setText("Available Doctor's");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 245, 34));

        doctors_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Full_name", "Gender", "Degree", "Speciality", "Patients", "Phone", "Address"
            }
        ));
        jScrollPane1.setViewportView(doctors_table);

        javax.swing.GroupLayout jPanel_doctorsLayout = new javax.swing.GroupLayout(jPanel_doctors);
        jPanel_doctors.setLayout(jPanel_doctorsLayout);
        jPanel_doctorsLayout.setHorizontalGroup(
            jPanel_doctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_doctorsLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_doctorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_doctorsLayout.setVerticalGroup(
            jPanel_doctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_doctorsLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pnlBody.add(jPanel_doctors, "card3");

        jPanel_userqueries.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel1.setText("User queries");
        jPanel_userqueries.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, 194, 45));
        jPanel_userqueries.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 660, 20));

        jScrollPane2.setBorder(null);

        jTable_queries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "username", "Email", "Query"
            }
        ));
        jScrollPane2.setViewportView(jTable_queries);

        jPanel_userqueries.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 670, 400));

        pnlBody.add(jPanel_userqueries, "card2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        pnlBody.add(jPanel3, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(819, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 129, Short.MAX_VALUE)
                    .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_doctorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_doctorsMouseClicked

        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(jPanel_doctors);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_lbl_doctorsMouseClicked

    private void lbl_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usersMouseClicked
        pnlBody.removeAll();
        pnlBody.repaint();
        pnlBody.revalidate();
        pnlBody.add(jPanel_userqueries);
        pnlBody.repaint();
        pnlBody.revalidate();
        
          

    }//GEN-LAST:event_lbl_usersMouseClicked

    private void lbl_doctorsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_doctorsMouseEntered
        
    }//GEN-LAST:event_lbl_doctorsMouseEntered

    private void lbl_usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usersMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_usersMouseEntered
   
    Connection conn;
    PreparedStatement st;
    public void table_update1(){
    int c;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3344/registration","root","");
           
            st = (PreparedStatement) conn.prepareStatement("SELECT * FROM `queries`");
           
            ResultSet rs = st.executeQuery();
            ResultSetMetaData rrs = (ResultSetMetaData) rs.getMetaData();
            c = rrs.getColumnCount();

            DefaultTableModel tblModel = (DefaultTableModel)jTable_queries.getModel();
            tblModel.setRowCount(0);
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int a=1;a<=c;a++)
                {
                    v2.add(rs.getString("username"));
                    v2.add(rs.getString("email"));
                    v2.add(rs.getString("query"));
                   

                }
                tblModel.addRow(v2);

            }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            System.out.println(e.getMessage());
        }
    }
    
    Connection con1;
    PreparedStatement ps;
    Connection conn1;
    PreparedStatement ps1;
    public void table_update(){
    int b;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3344/registration","root","");
           
            ps1 = (PreparedStatement) conn1.prepareStatement("SELECT * FROM `doctors`");
           
            ResultSet rs1 = ps1.executeQuery();
            ResultSetMetaData rrs1 = (ResultSetMetaData) rs1.getMetaData();
            b = rrs1.getColumnCount();

            DefaultTableModel tblModel = (DefaultTableModel)doctors_table.getModel();
            tblModel.setRowCount(0);
            while(rs1.next())
            {
                Vector v2 = new Vector();
                for(int a=1;a<=b;a++)
                {
                
                    v2.add(rs1.getString("Full_Name"));
                    v2.add(rs1.getString("gender"));
                    v2.add(rs1.getString("degree"));
                    v2.add(rs1.getString("sp_in"));
                    v2.add(rs1.getString("patients_cured"));
                    v2.add(rs1.getString("phn_no"));
                    v2.add(rs1.getString("hospital_address"));

                }
                tblModel.addRow(v2);

            }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            System.out.println(e.getMessage());
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adminpage1;
    private javax.swing.JTable doctors_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_doctors;
    private javax.swing.JPanel jPanel_userqueries;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable_queries;
    private javax.swing.JLabel lbl_doctors;
    private javax.swing.JLabel lbl_users;
    private javax.swing.JPanel pnlBody;
    // End of variables declaration//GEN-END:variables
}
