/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snap.care;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Atharva More
 */
public class Login_form extends javax.swing.JFrame {

    /**
     * Creates new form Login_form
     */
    public Login_form() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupmainpanel = new javax.swing.JPanel();
        reg1 = new javax.swing.JLabel();
        reg = new javax.swing.JLabel();
        jButton_Login1 = new javax.swing.JLabel();
        Closebtn = new javax.swing.JLabel();
        seperator1 = new javax.swing.JSeparator();
        seperator2 = new javax.swing.JSeparator();
        Lock_icon = new javax.swing.JLabel();
        User_icon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jTextField_Username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        signupbgpanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("signin");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupmainpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg1.setForeground(new java.awt.Color(52, 152, 219));
        reg1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reg1.setText("Register Now!");
        reg1.setToolTipText("");
        reg1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reg1MouseClicked(evt);
            }
        });
        signupmainpanel.add(reg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 80, 30));

        reg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reg.setText("Don't have a account yet?");
        signupmainpanel.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 140, 30));

        jButton_Login1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_Login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signin button.png"))); // NOI18N
        jButton_Login1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Login1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_Login1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_Login1MouseExited(evt);
            }
        });
        signupmainpanel.add(jButton_Login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 90, 30));

        Closebtn.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        Closebtn.setForeground(new java.awt.Color(204, 41, 54));
        Closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Closebtn.setText("X");
        Closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosebtnMouseClicked(evt);
            }
        });
        signupmainpanel.add(Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 20, -1));
        signupmainpanel.add(seperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 200, 10));
        signupmainpanel.add(seperator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 200, 10));

        Lock_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lock_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lock icon.png"))); // NOI18N
        signupmainpanel.add(Lock_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 30, 30));

        User_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user icon.png"))); // NOI18N
        signupmainpanel.add(User_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 30, 30));

        jLabel3.setFont(new java.awt.Font("Monument Extended", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 239, 244));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>SIGN IN TO<br>\nCONTINUE</html>");
        signupmainpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 250, 280, 60));

        jPasswordField.setBackground(new java.awt.Color(240, 239, 244));
        jPasswordField.setFont(jPasswordField.getFont().deriveFont(jPasswordField.getFont().getSize()+3f));
        jPasswordField.setForeground(new java.awt.Color(72, 67, 73));
        jPasswordField.setText("password");
        jPasswordField.setBorder(null);
        jPasswordField.setSelectionColor(new java.awt.Color(204, 41, 54));
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });
        signupmainpanel.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 260, 30));

        jTextField_Username.setBackground(new java.awt.Color(240, 239, 244));
        jTextField_Username.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jTextField_Username.setForeground(new java.awt.Color(72, 67, 73));
        jTextField_Username.setText("Username");
        jTextField_Username.setBorder(null);
        jTextField_Username.setSelectionColor(new java.awt.Color(204, 41, 54));
        jTextField_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusLost(evt);
            }
        });
        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });
        signupmainpanel.add(jTextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 260, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Monument Extended", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 41, 54));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIGN IN");
        signupmainpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 120, 40));

        signupbgpanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signupbgpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/650x350 straight corners.png"))); // NOI18N
        signupmainpanel.add(signupbgpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 350));

        getContentPane().add(signupmainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsernameActionPerformed

    private void ClosebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosebtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ClosebtnMouseClicked

    private void jTextField_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusGained
        if(jTextField_Username.getText().trim().toLowerCase().equals("username"))
        {
            jTextField_Username.setText("");
            jTextField_Username.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_UsernameFocusGained

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
        String pass = String.valueOf(jPasswordField.getPassword());
        
        if(pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField.setText("");
            jPasswordField.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jTextField_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusLost
         if(jTextField_Username.getText().trim().equals("") || 
           jTextField_Username.getText().trim().toLowerCase().equals("username"))
        {
            jTextField_Username.setText("username");
            jTextField_Username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_UsernameFocusLost

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
          String pass = String.valueOf(jPasswordField.getPassword());
        
        if(pass.trim().equals("") || 
           pass.trim().toLowerCase().equals("password"))
        {
            jPasswordField.setText("password");
            jPasswordField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordFieldFocusLost

    private void jButton_Login1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Login1MouseClicked
        java.sql.PreparedStatement st;
        java.sql.ResultSet rs;
        
        // get the username & password
        String username = jTextField_Username.getText();                    
        String password = String.valueOf(jPasswordField.getPassword());
        
        //create a select query to check if the username and the password exist in the database
        String query = "SELECT * FROM `users_db` WHERE `username` = ? AND `password` = ?";  
        
        // show a message if the username or the password fields are empty
        if(username.trim().equals("username"))
        {
            JOptionPane.showMessageDialog(null, "Enter Your Username", "Empty Username", 2);
        }
        else if(password.trim().equals("password"))
        {
            JOptionPane.showMessageDialog(null, "Enter Your Password", "Empty Password", 2);
        }
        else{
            
            try {
            st = My_CNX.getConnection().prepareStatement(query);
            
            st.setString(1, username);
            st.setString(2, password);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                // show a new form
                Dashboard form = new Dashboard();                
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                // close the current form(login form)
                this.dispose();
                
            }else{
                // error message
                JOptionPane.showMessageDialog(null, "Invalid Username / Password","Login Error",2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_form.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
        
        
    }//GEN-LAST:event_jButton_Login1MouseClicked

    private void jButton_Login1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Login1MouseEntered
        jButton_Login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signin button hover.png")));
    }//GEN-LAST:event_jButton_Login1MouseEntered

    private void jButton_Login1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Login1MouseExited
        jButton_Login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signin button.png")));
    }//GEN-LAST:event_jButton_Login1MouseExited

    private void reg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg1MouseClicked
                Registration rt= new Registration();
                rt.setVisible(true);
                rt.pack();
                rt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
    }//GEN-LAST:event_reg1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            new Login_form().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Closebtn;
    private javax.swing.JLabel Lock_icon;
    private javax.swing.JLabel User_icon;
    private javax.swing.JLabel jButton_Login1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_Username;
    private javax.swing.JLabel reg;
    private javax.swing.JLabel reg1;
    private javax.swing.JSeparator seperator1;
    private javax.swing.JSeparator seperator2;
    private javax.swing.JLabel signupbgpanel;
    private javax.swing.JPanel signupmainpanel;
    // End of variables declaration//GEN-END:variables
}
